name: 'openvpn'
description: ''
inputs:
  openvpn_config:
    description: ''
    required: true
  validation_ip:
    description: ''
    required: true
    default: 10.102.0.5
runs:
  using: 'composite'
  steps:
    - run: sudo apt-get update
      shell: bash 
    - run: sudo apt-get install -y openvpn traceroute
      shell: bash
    - run: echo ${{ inputs.openvpn_config }} | base64 -d | sudo tee /etc/openvpn/client/client.conf > /dev/null
      shell: bash
    - run: sudo systemctl start openvpn-client@client || journalctl -xefu openvpn-client@client
      shell: bash
    - run: sudo traceroute -m 2 -T ${{ inputs.validation_ip }}
      shell: bash